name: Hello Actions world

on: 
  workflow_dispatch:
  push:
    branches:
     - main

jobs:
  hello-actions:
    runs-on: ubuntu-20.04
    steps:
      - name: say-hello
        run: echo "Hello, Actions world!"
