name: Hello Actions world

on: 
  workflow_dispatch:
  push:
    branches:
     - main

jobs:
  hello-actions:
    runs-on: ubuntu-20.04
    steps:
      - name: say-hello
        run: echo "Hello, Actions world!"

  setup-spack:
    runs-on: ubuntu-20.04
    steps:
      - name: setup-spack
        shell: bash
        run: |
          sudo apt-get install cmake
          cmake --version
          sudo env
          spack ~/.spack work_regtest

