name: Hello Actions world

on: 
  workflow_dispatch:
  push:
    branches:
     - main

jobs:
  hello-actions:
    runs-on: ubuntu-20.04
    steps:
      - name: say-hello
        run: echo "Hello, Actions world!"

  setup-spack:
    runs-on: ubuntu-20.04
    steps:
      - name: setup-spack
        shell: bash
        run: |
          sudo apt-get install cmake
          cmake --version
          sudo env
          git clone -c feature.manyFiles=true https://github.com/MatthewMasarik-NOAA/gh-actions-regtest.git
          git clone -c feature.manyFiles=true https://github.com/JCSDA/spack.git
          ls *
          source spack/share/spack/setup-env.sh
          spack env create ww3-gnu gh-actions-regtest/model/ci/spack_gnu_serial.yaml
          spack compiler find
          spack external find cmake
          cmake --version
          spack concretize
          spack install --dirty
          sudo env
          
